#!/bin/sh

# Alias for startx
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# Aliasses for common system commands requiring sudo
for cmd in mount unmount pacman su ; do
	alias $cmd="sudo $cmd"
done

# Common aliases for verbosity
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkdir="mkdir -pv"

# Elable color options
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto"

# File aliases (zsh only)
alias -g \
	aliasrc=${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliasrc \
	profile=${XDG_CONFIG_HOME:-$HOME/.config}/shell/profile \
	zshrc=${XDG_CONFIG_HOME:-$HOME/.config}/zsh/.zshrc \
	vimrc=${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc \
	xprofile=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile \
	xinitrc=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc \
	xresources=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources \
	colors=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources.d/colors \
	urxvt=${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources.d/urxvt \
	awesomerc=${XDG_CONFIG_HOME:-$HOME/.config}/awesome/rc.lua \

# Other random crap
alias weather="curl wrrt.in"

alias dotfiles='git --git-dir=$HOME/.dots/ --work-tree=$HOME'
