#!/bin/sh

# Profile file runs on login. Enviroment Variables set here

# Add `~/.local/bin to $PATH
localbin=$(find $HOME/.local/bin -type d -printf "%p:")
export PATH="$PATH:${localbin%%:}" # split up in to 2 lines cus bash is stupid

# Default programs
export EDITOR="vim"
export TERMINAL="urxvt"
#export BROWSER="firefox"

# XDG
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Xorg
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"

# Less
export LESSHISTFILE="-"

# Shell
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

# Rust
export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"

# Vim
export VIMINIT="if has('nvim') | so ${XDG_CONFIG_HOME:-$HOME/.config}/nvim/init.lua | else | set nocp | so ${XDG_CONFIG_HOME:-$HOME/.config}/vim/vimrc | endif"

# Start the graphical server if logging in on tty1
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC" && echo "Starting X"
