#!/bin/sh

#/!bin/sh

# for virtualbox only
xrandr --newmode "1920x1080" 172.80 1920 2040 2248 2576 1080 1081 1084 1118 -Hsync +Vsync
xrandr --addmode Virtual-1 1920x1080
xrandr --output Virtual-1 --mode 1920x1080

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11.xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11.xprofile"
else
	. "$HOME/.xprofile"
fi

exec awesome
