#!/bin/sh

# WM/DE independant autostart

# Start if not already running function
start() {
	cmd=$1; shift
	args=$*
	pgrep -u "$USER" -ic "$cmd" > /dev/null || $cmd $args &
}

# Start with terminal if not already running function
termstart() {
	cmd=$1; shift
	args=$*
	pgrep -u "$USER" -ic "$cmd" > /dev/null || $TERMINAL -e $cmd $args &
}

# Place autostart applications here
start setbg
start picom
